// OpenClient.idl: ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 生成类型库(OpenClient.tlb)，该类型库将成为
// OpenClient.ocx。

#include <olectl.h>
#include <idispids.h>

[ uuid(a477ac36-5df8-4fad-8ca6-613af8a2e450), version(1.0),
  control ]
library OpenClientLib
{
	importlib(STDOLE_TLB);

	//  COpenClientCtrl 的主调度接口
	[ 
		uuid(7259c739-a75e-4d3a-ae4b-ec815be824da)
	]
	dispinterface _DOpenClient
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
			int OpenMainFrame();
	};

	//  COpenClientCtrl 的事件调度接口

	[ 
		uuid(47267c73-e3bc-43fb-ace8-b91687cb984b)
	]
	dispinterface _DOpenClientEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  COpenClientCtrl 的类信息
	[
		uuid(1c40c893-4ad4-48af-9f35-87867b486e31)
	]
	coclass OpenClient
	{
		[default] dispinterface _DOpenClient;
		[default, source] dispinterface _DOpenClientEvents;
	};

};

